###Ping Request to see whether connecting to server. Should return pong
GET http://localhost:3000/ping

###Create a new user
POST http://localhost:3000/authentication/create_account
Content-Type: application/json

{
    "email": "aa1111a@student.american.edu",
    "password" : "fakePass11"
}