###Ping Request to see whether connecting to server. Should return pong
GET http://localhost:3000/ping

###Create a new user
POST http://localhost:3000/authentication/user_create
Content-Type: application/json

{
    "email": "ab111a@st2udent.american.edu",
    "password" : "fakePass123123123"
}